baseURL = "https://surfacesyntacticud.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "SUD"
theme = "cayman-hugo-theme"

enableEmoji = "true"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = "SUD"
  project_tagline = "Surface Syntactic Universal Dependencies"


  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#ff0000"
  header_background_color_secondary = "#155799"

  # Text colors
  section_headings_color = "#ff0000"
  body_text_color = "black"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Guidelines"
    url = "https://guidelines.surfacesyntacticud.org/"
    weight = 2
  [[menu.nav]]
    name = "Discusssions"
    url = "https://github.com/surfacesyntacticud/guidelines/issues"
    weight = 2
  [[menu.nav]]
    name = "SUD Corpora"
    url = "/data/"
    weight = 3
  [[menu.nav]]
    name = "Comparison with UD"
    url = "/conversions"
    weight = 4
  [[menu.nav]]
    name = "GitHub project"
    url = "https://github.com/surfacesyntacticud"
    weight = 5
